### PR TITLE
fix: vcf2abook - append vcf to addressbook, if addressbook exists

### PR DESCRIPTION
**Pull request by tjex**
`vcf2abook` overwrites the address book. Is there an `append` function or flag? I didn't spot any.

Added .gitignore with `.DS.Store` entry for mac.

### CODE REVIEW

**Comment by jspricke** [comment]
This sounds like a bug and we should probably read in old data before writing new. Are you interested in fixing this properly? Otherwise I can have a look, later.

**Comment by tjex** [comment]
I'm interested, for the sake of practicing some python.
But the issue then arrises of dealing with duplicates, so the task might blow out for me (I'm a bit of a novice tbh)...

If you were prepared to help me chip away at it via a slightly verbose PR then that would be an option.

But if it's something you could just nail quickly and would prefer that route, then that's also something to consider.

**Comment by jspricke** [comment]
I guess we could do something like:
```Python
if os.path.isfile(args.outfile):
    abook = Abook(args.outfile)
    for vcard in args.infile:
        if vcard in abook.get_uids():
            abook.replace_vobject(vcard)
        else:
            abook.append_vobject(vcard)
```

**Comment by tjex** [comment]
Makes sense. Well, I can at least have a crack and will be able to get _at least_ part way, which should help.

**Comment by jspricke** [comment]
It is probably easier to reset your branch to the current master state, i.e. (with origin pointing to the original repo):
```
git fetch origin
git reset --hard origin/master
```
Or even better to open a topic branch with `git checkout -b topic`.

Also, `.gitignore` should not contain non project paths, you can add it to you your `$XDG_CONFIG_HOME/git/ignore`.

**Comment by tjex** [comment]
alright. But still on my fork right?
Can't believe .DS.Store wasn't in my global gitignore... thanks.

**Comment by jspricke** [comment]
> alright. But still on my fork right?

Not sure what you are talking about here.

**Comment by tjex** [comment]
my fork of your repo: https://github.com/tjex/python-abook/tree/master

I just got confused by your instruction to "reset my branch to the current master state", because my current master state is the current state of the master on my branch, _on my fork_. 

I.e. when I run `git fetch origin && git reset --hard origin/master`, nothing gets reset, because I'm already at HEAD (on my fork).

As, as far as I know, I can't clone the main repo, make a branch and push to your repo?

**Comment by jspricke** [comment]
> my fork of your repo: https://github.com/tjex/python-abook/tree/master
> 
> I just got confused by your instruction to "reset my branch to the current master state", because my current master state is the current state of the master on my branch, _on my fork_.
> 
> I.e. when I run `git fetch origin && git reset --hard origin/master`, nothing gets reset, because I'm already at HEAD (on my fork).

That's why I wrote: "with origin pointing to the original repo". I.e. normally you have origin pointing to this repo and tjex pointing to your remote.

> As, as far as I know, I can't clone the main repo, make a branch and push to your repo?

Right.

**Comment by tjex** [comment]
Aha. Cool. So this?:


Screenshot 2023-09-27 at 14 34 49

**Comment by jspricke** [comment]
Yes, but you probably also want: `git remote add tjex git@github.com:tjex/python-abook.git` So you can do `git push tjex`

**Comment by jspricke** [comment]
So normally you would do:
```Shell
git clone https://github.com/jspricke/python-abook.git
cd python-abook
git remote add tjex git@github.com:tjex/python-abook.git
git checkout -b vcf2abook-append
#edit file
git commit
git push tjex
hub pull-request
```

Also, please send data as text, not screen shots.

**Comment by tjex** [comment]
Excellent. Thanks! Will do re screenshots / text

**Comment by tjex** [comment]
I'll close this now then so I can make a new pr from a specific branch.

**Pull request closed without merging**
